version: '3'
includes:
  docker: tasks/Taskfile.docker.yaml
  helm: tasks/Taskfile.helm.yaml
  secret: tasks/Taskfile.secret.yaml
tasks:
  setup:
    desc: Setup the repository
    cmds:
      - ./scripts/ci/setup.sh
      - ./scripts/local/secrets.sh
  lint:
    desc: Lints the whole code-base
    cmds:
      - pre-commit run --all-files
