version: '3'
tasks:
  fetch:
    desc: 'Fetch secrets from Infisical'
    cmds:
      - INFISICAL_API_URL="https://secrets.atomi.cloud" infisical run --env=dev -- true
  scan:
    desc: 'Scan for hardcoded secrets'
    cmds:
      - infisical scan
