name: CD
on:
  push:
    tags:
      - v*.*.*
      - v*.*.*
      - v*.*.*
jobs:
  placeholder:
    name: Placeholder CD
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder Step
        run: echo "Placeholder step ${{ github.ref_name }}"
  docker:
    name: Docker Image
    uses: ./.github/workflows/⚡reusable-docker.yaml
    secrets: inherit
    with:
      image_name: try-template
      dockerfile: ./infra/Dockerfile
      version: ${{ github.ref_name }}
  helm:
    name: Helm Chart
    uses: ./.github/workflows/⚡reusable-helm.yaml
    secrets: inherit
    with:
      chart_path: ./infra/root_chart
      version: ${{ github.ref_name }}
