name: CI
on:
  push: null
jobs:
  precommit:
    name: Pre-Commit
    uses: ./.github/workflows/⚡reusable-precommit.yaml
    secrets: inherit
  docker:
    name: Docker Image
    uses: ./.github/workflows/⚡reusable-docker.yaml
    secrets: inherit
    with:
      image_name: try-template
      dockerfile: ./infra/Dockerfile
  helm:
    name: Helm Chart
    uses: ./.github/workflows/⚡reusable-helm.yaml
    secrets: inherit
    with:
      chart_path: ./infra/root_chart
