name: ⚡ Reusable Pre-Commit
on:
  workflow_call:
jobs:
  precommit:
    name: Pre-Commit
    runs-on:
      - nscloud-ubuntu-22.04-amd64-32x64-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-atomi-nix-store-cache
    steps:
      - uses: actions/checkout@v6
      - uses: AtomiCloud/actions.setup-nix@v2
        with:
          checkout: false
      - name: Run pre-commit
        run: nix develop .#ci -c ./scripts/ci/pre-commit.sh
